### ISSUE TITLE
Sorting - intersection or two arrays

### ISSUE THREAD

**Issue by bar-d** [bar-d/AlgorithmStudy#14]
[intersection or two arrays](https://leetcode.com/problems/intersection-of-two-arrays/)

**Comment by Wody95** [comment]
```swift
func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
    return Array(Set(nums1).intersection(Set(nums2)))
}
```

**Comment by doyeonjeong** [comment]
```swift
// 349. Intersection of Two Arrays
class Solution {
    func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
        let numberSet1: Set = Set(nums1)
        var numberSet2: Set = Set(nums2)
        return Array(numberSet2.intersection(numberSet1)).sorted()
    }
}
```

**Comment by MINRYUL** [comment]
```swift
func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
    return Array(Set(nums1).intersection(Set(nums2)))
}
```

**Comment by kimjm010** [comment]
class Solution {
    func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
        var result: [Int] = []
        let sortedNums2 = nums2.sorted()

        for i in 0..<nums1.count {
            if sortedNums2.count != 0 {
                if sortedNums2.contains(nums1[i]) {
                    result.append(nums1[i])
                    continue
                }
            }
        }

        return Array(Set(result))
    }
}

**Comment by kimjm010** [comment]
`func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
        var result: [Int] = []
        let sortedNums2 = nums2.sorted()

        for i in 0..<nums1.count {
            if sortedNums2.count != 0 {
                if sortedNums2.contains(nums1[i]) {
                    result.append(nums1[i])
                    continue
                }
            }
        }

        return Array(Set(result))
    }`

**Comment by kimjm010** [comment]
`func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
        var result: [Int] = []
        let sortedNums2 = nums2.sorted()

        for i in 0..<nums1.count {
            if sortedNums2.count != 0 {
                if sortedNums2.contains(nums1[i]) {
                    result.append(nums1[i])
                    continue
                }
            }
        }

        return Array(Set(result))
    }`

**Comment by kimjm010** [comment]
```Swift
func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
        var result: [Int] = []
        let sortedNums2 = nums2.sorted()

        for i in 0..<nums1.count {
            if sortedNums2.count != 0 {
                if sortedNums2.contains(nums1[i]) {
                    result.append(nums1[i])
                    continue
                }
            }
        }

        return Array(Set(result))
    }
```

**Comment by bar-d** [comment]
```swift 
func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
    var nums1Set = Set(nums1)
    var nums2Set = Set(nums2)
    
    return Array(nums1Set.intersection(nums2Set))
}
```

**Comment by hongssup** [comment]
```Swift
func intersection(_ nums1: [Int], _ nums2: [Int]) -> [Int] {
    return Array(Set(nums1).intersection(nums2))
}
```
정렬과 무슨 상관인지 모르겠습니다,,
