### ISSUE TITLE
Greedy - minimum number of swaps to make the string balanced

### ISSUE THREAD

**Issue by bar-d** [bar-d/AlgorithmStudy#28]
[minimum number of swaps to make the string balanced](https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-string-balanced/)

**Comment by MINRYUL** [comment]
func minSwaps(_ s: String) -> Int {
        var s = Array(s), left = 0, right = 0

        s.forEach { c in
            switch c {
                case "]":
                    if left > 0 { left -= 1 }
                    else { right += 1 }
                default:
                    left += 1
            }
        }
        return (right + 1)/2
    }

**Comment by doyeonjeong** [comment]
```swift
func minSwaps(_ s: String) -> Int {
    var swaps = 0
    var imbalance = 0

    for char in s {
        if char == "[" {
            imbalance += 1
        } else {
            imbalance -= 1

            if imbalance < 0 {
                swaps += 1
                imbalance = 1
            }
        }
    }
    return swaps
}
```
