### ISSUE TITLE
Dynamic Programming - fibonacci number

### ISSUE THREAD

**Issue by bar-d** [bar-d/AlgorithmStudy#37]
[fibonacci number](https://leetcode.com/problems/fibonacci-number/)

**Comment by dp221125** [comment]
func fib(_ n: Int) -> Int {
        if n == 0 {
            return 0
        } else if n == 1 {
            return 1
        } else {
            return (2 ... n).reduce(into: [0, 1]) { partialResult, _ in
                let numberOfPartialResult = partialResult.count
                return partialResult.append(partialResult[numberOfPartialResult - 2] + partialResult[numberOfPartialResult - 1])
            }.last!
        }
    }

**Comment by ArinNigam** [comment]
class Solution {
public:
		int dp[35];
		int func(int n){
			if (n<2){
				return n;
			}
			if (dp[n]!=-1){
				return dp[n];
			}
			return dp[n]=fib(n-1)+fib(n-2);
		}
    int fib(int n) {
				memset(dp,-1,sizeof(dp));
				return func(n);
    }
};

**Comment by ArinNigam** [comment]
```c++
class Solution {
public:
        int dp[35];
        int func(int n){
	if (n<2){
              return n;
	}
	if (dp[n]!=-1){
              return dp[n];
	}
	return dp[n]=fib(n-1)+fib(n-2);
        }

        int fib(int n) {
              memset(dp,-1,sizeof(dp));
              return func(n);
        }
};
```
